// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_Items(arg1:string,arg2:number):Promise<Array<string>>;

export function Get_Sent():Promise<Array<string>>;

export function Is_Setup():Promise<boolean>;

export function Launch_Smtp_Server(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Refresh_Inbox():Promise<void>;

export function Send_Email(arg1:string,arg2:string,arg3:string):Promise<void>;
