// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_Inbox():Promise<string>;

export function Launch_Smtp_Server(arg1:string,arg2:string,arg3:string):Promise<void>;
